version: "3"
services:
  reverse_proxy:
    image: cesar18pena/reverse-proxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - user-service

  user-service:
    image: cesar18pena/user-service
    environment:
      POSTGRESS_USERNAME: user
      POSTGRESS_PASSWORD: password
      POSTGRESS_DB: db
      POSTGRESS_HOST: postgres
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    depends_on:
      - postgresql_db

  postgresql_db:
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    image: postgres
    ports:
      - 5432:5432
    logging:
      driver: "none"
